future-architect/cheetah-grid

src/js/core/DrawGrid.js, src/js/internal/hiDPI.js, src/js/internal/utils.js, webpack/test/font-svg-to-icons-js-loader/test.js, webpack/test/svg-to-icon-js-loader/loader-test-mdi.js
=> [fix] blurry on Retina Display

.gitignore, src/js/GridCanvasHelper.js, src/js/ListGrid.js, src/js/core/DrawGrid.js, src/js/themes/theme.js, src/test/ListGrid_sample.js
=> [add]  font to theme setting

src/js/GridCanvasHelper.js, src/js/ListGrid.js, src/js/core/DrawGrid.js, src/js/themes/BASIC.js, src/js/themes/MATERIAL_DESIGN.js, src/js/themes/theme.js
=> [add] underlay background color setting

src/js/GridCanvasHelper.js, src/js/columns/style/Style.js, src/js/columns/type/ButtonColumn.js, src/js/columns/type/Column.js, src/js/core/DrawGrid.js, src/js/header/type/SortHeader.js, src/js/internal/calc.js, src/js/tools/canvashelper.js, src/test/ListGrid_sample.js, src/test/specs/internal/calc_spec.js
=> [add] padding to text styles

docs/src/demos/usage/column_types.html.hbs, docs/src/demos/usage/column_types/Classes.html.hbs, docs/src/demos/usage/column_types/MultilineTextColumn.html.hbs, eslint/eslint-config.js, src/js/GridCanvasHelper.js, src/js/columns/style/MultilineTextStyle.js, src/js/columns/type.js, src/js/columns/type/MenuColumn.js, src/js/columns/type/MultilineTextColumn.js, src/js/core/DrawGrid.js, src/js/element/Inline.js, src/js/element/InlineDrawer.js, src/js/element/InlineIcon.js, src/js/element/InlineImage.js, src/js/element/InlinePath2D.js, src/js/element/inlines.js, src/js/header/type/SortHeader.js, src/js/internal/canvases.js, src/js/tools/canvashelper.js
Make display multiline text in cell  
close #37
=> [add] MultilineTextColumn

docs/build.js, docs/handlebars/helpers.js, docs/src/css/style.css, docs/src/demos/faq/filter.html.hbs, docs/src/demos/usage/datasource/FilterDataSource.html.hbs, docs/src/demos/usage/grid_data.html.hbs, docs/src/demos/usage/using_promises.html.hbs, docs/src/index.html.hbs, src/js/columns/type/BaseColumn.js, src/js/core/DrawGrid.js, src/js/data.js, src/js/data/CachedDataSource.js, src/js/data/DataSource.js, src/js/data/FilterDataSource.js
Add a filtering feature for grid data
close #44
=> [add] FilterDataSource

packages/cheetah-grid/src/js/columns/action/internal/InlineInputElement.js, packages/cheetah-grid/src/js/columns/action/internal/SmallDialogInputElement.js, packages/cheetah-grid/src/js/core/DrawGrid.js, packages/demo/package-lock.json, packages/demo/src/vue/EnterprisePage.vue, packages/vue-cheetah-grid/package-lock.json
=> Fixed that can not input cells with Hangul IME.

README.md, docs/0.6/demos/usage/column_styles.html, docs/0.6/ja/demos/usage/column_styles.html, docs/0.6/jsdoc/index.html, packages/docs/src/demos/usage/column_styles.html.hbs
=> Docs add header style

packages/cheetah-grid/package.json, packages/cheetah-grid/src/js/themes.js
=> - Fixed: the global theme was not reflected in the instance after grid generation.

packages/cheetah-grid/index.d.ts
Add typings for typescript. Issue:  #104
=> Add typings for typescript

packages/cheetah-grid/index.d.ts
I confirmed the following code works.
```ts
import cheetahGrid from "cheetah-grid";
console.log(cheetahGrid);
```
=> fix index.d.ts

packages/cheetah-grid/index.d.ts
add template parameter of source to TypeScript types.
fix columnType, action to accept string.
fix DataSource types.
=> Fix TypeScript type definition

.travis.yml, packages/cheetah-grid/package-lock.json, packages/cheetah-grid/package.json, packages/cheetah-grid/src/js/header/action.js, packages/docs/api/js/advanced_header/column_sort.md
=> Fixed custom sort function does not work

packages/cheetah-grid/src/js/GridCanvasHelper.ts, packages/cheetah-grid/src/js/themes/theme.ts, packages/cheetah-grid/src/js/ts-types/plugin.ts, packages/docs/api/js/theme.md
=> Add highlightBgColor property to theme

packages/cheetah-grid/src/js/core/DrawGrid.ts, packages/cheetah-grid/src/js/ts-types/grid-engine.ts, packages/cheetah-grid/src/test/specs/DrawGrid_visibleCount.html, packages/cheetah-grid/src/test/specs/DrawGrid_visibleCount_spec.js
=> Add `visibleRowCount`, `visibleColCount`, `topRow` and `leftCol` properties to grid

packages/docs/api/js/grid_data/FilterDataSource.md
=> Update doc of FilterDataSource

packages/cheetah-grid/src/js/columns/action/InlineMenuEditor.ts, packages/cheetah-grid/src/js/columns/action/internal/InlineMenuElement.ts, packages/cheetah-grid/src/js/columns/type/MenuColumn.ts, packages/cheetah-grid/src/js/internal/menu-items.ts, packages/cheetah-grid/src/js/ts-types/column/action.ts, packages/cheetah-grid/src/js/ts-types/define.ts, packages/cheetah-grid/src/test/ListGrid_sample_for_layout.js, packages/docs/api/js/cell_message.md, packages/docs/api/js/column_actions/InlineMenuEditor.md, packages/docs/api/js/column_types/MenuColumn.md, packages/docs/api/js/options/allowRangePaste.md, packages/vue-cheetah-grid/lib/CGridMenuColumn.vue, packages/vue-cheetah-grid/test/Sample.vue, packages/vue-cheetah-grid/test/sample.spec.js
- Changed InlineMenuEditor to change selectable options for each record.
- Changed to display label of menu option from "caption" to "label".
=> Changed InlineMenuEditor to change selectable options for each record.

packages/cheetah-grid/src/js/ListGrid.ts
=> Extract headerRowHeight property properly

packages/cheetah-grid/package.json, packages/cheetah-grid/src/js/data/DataSource.ts, packages/cheetah-grid/src/js/internal/imgs.ts
=> Fixed not to add timestamp to load images.

packages/cheetah-grid/package-lock.json, packages/cheetah-grid/package.json, packages/demo/package-lock.json, packages/demo/package.json, packages/docs/.vuepress/config.js, packages/vue-cheetah-grid/package-lock.json, packages/vue-cheetah-grid/package.json
=> Fix broken document page

packages/cheetah-grid/src/js/list-grid/layout-map/api.ts
discussion: https://twitter.com/shibu_jp/status/1453673741506932739
=> move width/minWidth/maxWidth to BaseHeaderDefine

packages/react-cheetah-grid/.npmignore, packages/react-cheetah-grid/CHANGES.md, packages/react-cheetah-grid/README.md, packages/react-cheetah-grid/package.json
- New: Add npm badge to README
- Fix: Remove unused file from npm package
=> Fix/react cheetah grid 0.2.1

packages/react-cheetah-grid/CHANGES.md, packages/react-cheetah-grid/package.json
=> react-cheetah-grid 0.2.2

packages/cheetah-grid/src/js/core/DrawGrid.ts, packages/cheetah-grid/src/js/ts-types/grid-engine.ts, packages/docs/api/js/options/README.md, packages/docs/api/vue/components/CGrid.md, packages/vue-cheetah-grid/lib/CGrid.vue
You can now change the destination cell by specifying a function.
=> Add function support to `keyboardOptions.moveCellOnX` option
